server:
  port: 8081

spring:
  application:
    name: incident-service
  datasource:
    url: jdbc:postgresql://localhost:5433/incidents
    username: opsboard
    password: opsboard
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

