sonar.projectName=OpsBoard DevOps
sonar.sourceEncoding=UTF-8

sonar.sources=backend/gateway/src/main,backend/incident-service/src/main,backend/team-service/src/main,frontend/src
sonar.tests=backend/gateway/src/test,backend/incident-service/src/test,backend/team-service/src/test,frontend/src
sonar.test.inclusions=**/*Test.java,**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/target/**,frontend/node_modules/**,frontend/.output/**,frontend/dist/**,frontend/src/routeTree.gen.ts
sonar.coverage.exclusions=**/*Application.java,frontend/src/router.tsx,frontend/src/routeTree.gen.ts,frontend/src/routes/__root.tsx,frontend/src/test/**
sonar.cpd.exclusions=frontend/src/routeTree.gen.ts

sonar.java.binaries=backend/gateway/target/classes,backend/incident-service/target/classes,backend/team-service/target/classes
sonar.java.test.binaries=backend/gateway/target/test-classes,backend/incident-service/target/test-classes,backend/team-service/target/test-classes
sonar.junit.reportPaths=backend/gateway/target/surefire-reports,backend/incident-service/target/surefire-reports,backend/team-service/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=backend/gateway/target/site/jacoco/jacoco.xml,backend/incident-service/target/site/jacoco/jacoco.xml,backend/team-service/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.tsconfigPaths=frontend/tsconfig.json
